#version 450 core

layout(location = 0) uniform float ThreadIDToTexcoord;

layout(binding = 0) uniform sampler3D VoxelSource;
layout(binding = 0, r8) restrict writeonly uniform image3D VoxelTarget;

layout (local_size_x = 8, local_size_y = 8, local_size_z = 8) in;
void main()
{
	vec4 filtered = textureLod(VoxelSource, (vec3(gl_GlobalInvocationID) + vec3(0.5)) * ThreadIDToTexcoord, 0);
	imageStore(VoxelTarget, ivec3(gl_GlobalInvocationID), filtered);
}